version: "2"


services:
    
    config.service:
        image: farmacia/config-service:latest
        restart: always
        container_name: config-service
        build: ./config-server/

    eureka.service:
        image: farmacia/eureka-service:latest
        restart: always
        container_name: eureka-service
        build: ./eureka-server/
        ports:
            - 8081:8080
        
    auth.service:
        image: farmacia/auth-service:latest
        restart: always
        container_name: auth-service
        build: ./auth-server/
        ports:
            - 8083:8080
        
    medicamento.service:
        image: farmacia/medicamento-service:latest
        restart: always
        container_name: medicamento-service
        build: ./medicamento-api/
        
    zuul.service:
        image: farmacia/zuul-service:latest
        restart: always
        container_name: zuul-service
        build: ./zuul/
        ports:
            - 8082:8080
    
    frontend:
        image: farmacia/frontend:latest
        restart: always
        container_name: frontend
        build: ./frontend/
        ports:
            - 8080:80
        
    memories:
        image: mysql:5.6
        container_name: memories
        environment:
            - MYSQL_ROOT_PASSWORD=root
    
    
            